crmaaf/apps/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('', views.index, name = 'index'),
    path('api/chart_data/', views.ChartAPIView.as_view()),
    path('orders/', views.OrdersListView.as_view(), name = 'orders'),

    path('orders/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('orders/<str:pk>', views.OrderDetailView.as_view(), name='order_detail'),
    path('orders/<str:pk>/print/', views.PrintOrderDetailView.as_view(), name='order_detail_print'),
    path('orders/<str:pk>/delete/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('orders/<str:pk>/update/', views.OrderUpdateView.as_view(), name='order_update'),

    path('orders/<int:pk>/deletefield/', views.inOrderDeleteView.as_view(), name='in_order_delete'),
    path('orders/<int:pk>/updatefield/', views.inOrderUpdateView.as_view(), name='in_order_update'),
    path('orders/<str:pk>/createfield/', views.inOrderCreateView.as_view(), name='in_order_create'),
    path('orders/<str:pk>/sendorder/', views.inSendOrder, name='in_order_send'),

    path('orders/<str:pk>/alloworder/', views.allowOrder, name='allow_order'),
    path('orders/<str:pk>/disalloworder/', views.disallowOrder, name='disallow_order'),
    path('orders/<str:pk>/allowOrderManager/', views.allowOrderManager, name='allow_order_manager'),

    path('company/', views.companyListView.as_view(), name = 'company'),
    path('company/create/', views.companyCreateView.as_view(), name = 'company_create'),
    path('company/<int:pk>/update/', views.companyUpdateView.as_view(), name = 'company_update'),
    path('company/<int:pk>/delete/', views.companyDeleteView.as_view(), name = 'company_delete'),

    path('product/', views.productListView.as_view(), name = 'product'),
    path('product/create/', views.productCreateView.as_view(), name = 'product_create'),
    path('product/<int:pk>/update/', views.productUpdateView.as_view(), name = 'product_update'),
    path('product/<int:pk>/delete/', views.productDeleteView.as_view(), name = 'product_delete'),

    path('transport/', views.transportListView.as_view(), name = 'transport'),
    path('transport/create/', views.transportCreateView.as_view(), name = 'transport_create'),
    path('transport/<int:pk>/update/', views.transportUpdateView.as_view(), name = 'transport_update'),
    path('transport/<int:pk>/delete/', views.transportDeleteView.as_view(), name = 'transport_delete'),

    path('shipment/', views.shipmentListView.as_view(), name = 'shipment'),
    path('shipment/create/', views.shipmentCreateView.as_view(), name = 'shipment_create'),
    path('shipment/<int:pk>/update/', views.shipmentUpdateView.as_view(), name = 'shipment_update'),
    path('shipment/<int:pk>/delete/', views.shipmentDeleteView.as_view(), name = 'shipment_delete'),
]

crmaaf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-interface/', include('rest_framework.urls')),

    path('railway/', include('crmaaf.apps.railwayplatform.urls')),
    path('core/', include('crmaaf.apps.core.urls')),
    path('', include('crmaaf.apps.aaf.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crmaaf/apps/core/models.py
from django.db import models
from django.urls import reverse 
from django.contrib.auth.models import User
from django.utils import timezone
import uuid


class Product(models.Model):
    """ Products our company like flour, molasses and etc.
    """

    name = models.CharField(max_length = 120, help_text = 'Напишите Названия Продукта', verbose_name = 'Наименнование')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        
    pass

class Transport(models.Model):
    """ Actually the model is transportation.
    """

    name = models.CharField(max_length = 120, help_text = 'Напишите назваиня Типа Транспортировки', verbose_name = 'Наименнование')
    controlling_transport = models.ManyToManyField(User, blank = True, help_text = 'Распоряжение получит', verbose_name = 'Распоряжение получит', related_name='controlling_transport')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']
        verbose_name = 'Транспортировка'
        verbose_name_plural = 'Транспортировки'

    pass

class Shipment(models.Model):
    """ Model for shipments types.
    """

    name = models.CharField(max_length = 120, help_text = 'Напишите названия отгрузки', verbose_name = 'Наименнование')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']
        verbose_name = 'Отгрузка груза'
        verbose_name_plural = 'Отгрузки груза'

    pass

class Company(models.Model):
    """ The company which will be added to the "order" list 
    and may for search by users any contacts information about company.
    """ 

    name = models.CharField(max_length = 120, help_text = 'Напишите названия Компании', verbose_name = 'Наименнование')
    contact_name = models.CharField(max_length = 120, help_text = 'Напишите Ф.И.О.', blank = True, verbose_name = 'Контактное Имя')
    contact_phone = models.CharField(max_length = 16, help_text = 'Напишите Номер Телефона', blank = True, verbose_name = 'Контактный Телефон')
    contact_email = models.EmailField(help_text = 'Укажите Адресс Электронной Почты', blank = True, verbose_name = 'Контактный Е-Майл')
    note = models.TextField(max_length = 1000, help_text = 'Введите Описание', blank = True, verbose_name = 'Заметки')

    class Meta:
        ordering = ['-name']
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

    def __str__(self):
        return self.name

    def get_absoulute_url(self):
        return reverse('company-detail', args=[str(self.id)])

    pass

class OrderInstance(models.Model):
    """  This is model will be group up all the "orders" 
    to the alone "order" with tables, "controlling users" list and etc.
    """

    title = models.CharField(max_length = 120, help_text = 'Наименнование распоряжения', verbose_name = 'Наименнование')
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, help_text = 'Уникальный ID', verbose_name = 'Уникальный ID')
    id_document = models.IntegerField(help_text = 'Уникальный ID', verbose_name = 'Уникальный ID', blank = True, default = 0)
    due_back = models.DateField(null = True, blank = True, verbose_name = 'Дата подачи распоряжения') 
    date_allow = models.DateField(null = True, blank = True, verbose_name = 'Дата согласования распоряжения')
    date_finish = models.DateField(null = True, blank = True, verbose_name = 'Дата исполнения распоряжения')

    controlling = models.ManyToManyField(User, blank = True, help_text = 'Распоряжение получит', verbose_name = 'Распоряжение получит', related_name = 'controlling')
    controlling_allow = models.ManyToManyField(User, blank = True, help_text = 'Распоряжение одобрил', verbose_name = 'Распоряжение одобрил', related_name = 'controlling_allow')
    controlling_disallow = models.ManyToManyField(User, blank = True, help_text = 'Распоряжение неодбрил', verbose_name = 'Распоряжение неодбрил', related_name = 'controlling_disallow')

    created_by = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = 'Исполнитель распоряжения', related_name = 'created_by')
    shipment_by = models.ForeignKey(Shipment, on_delete = models.CASCADE, help_text = 'Выберите отгрузку', blank = True, null=True, default=None, verbose_name = 'Отгрузка от', related_name = 'shipment_by')

    LOAN_STATUS = (
        ('p', 'В Процессе'),
        ('w', 'На согласование'),
        ('j', 'На исполнение'),
        ('a', 'Исполнено'),
        ('d', 'Отказано'),
    )

    LOAN_TYPE_ORDER = (
        ('kp', 'Паточный'),
        ('kz', 'Комбикормовый завод'),
        ('ml', 'Мельница'),
    )

    status = models.CharField(max_length = 16, choices = LOAN_STATUS, blank = True, default = 'p', verbose_name = 'Статус')
    type_order = models.CharField(max_length = 16, choices = LOAN_TYPE_ORDER, default = 'kp', verbose_name = 'Тип распоряжения')


    class Meta:
        ordering = ['-due_back', '-status']
        permissions = (("sign_order", "Can sign order"), ("sign_order_manager", "Sign order manager"),)
        verbose_name = 'Распоряжение'
        verbose_name_plural = 'Распоряжения'

    def display_created_by(self):
        self.full_name = '' #For if the user haven't name or last name.

        if self.created_by.last_login:
            self.full_name = self.full_name + f'{self.created_by.last_name}'
        if self.created_by.first_name:
            self.full_name = self.full_name + f' {self.created_by.first_name[0]}.'

        return self.full_name

    def __str__(self):
        return f'{self.title}'

    def get_absoulute_url(self):
        return reverse('order_detail', args=[str(self.id)])

    display_created_by.short_description = 'Создатель Распоряжения'
    pass

class Order(models.Model):
    """ This is class is table "order" it will be related to some "order instance",
    but mostly with one "order instance".
    """
    
    company = models.ForeignKey(Company, on_delete = models.CASCADE, verbose_name = 'Компания')
    products = models.ManyToManyField(Product, help_text = 'Выберите Продукт', verbose_name = 'Продукция')
    date_of_created = models.DateField(auto_now_add = True, verbose_name = 'Дата Создания')
    date_of_shipment = models.DateField(help_text = 'Укажите Дату Отгрузки', verbose_name = 'Дата Отгрузки')
    net_weight = models.DecimalField(max_digits = 19, decimal_places = 2, help_text = 'Введите вес', verbose_name = 'Вес Нетто, тн')
    transport_order = models.ForeignKey(Transport, on_delete = models.CASCADE, help_text = 'Выберите тип транспорортировки', verbose_name = 'Транспортировка')
    transport_number = models.IntegerField(blank = True, default = 0, help_text = 'Количество транспорта', verbose_name = 'Количество транспорта')
    note = models.TextField(max_length = 1000, help_text = 'Введите описание', blank = True, verbose_name = 'Заметки')
    order_by = models.ForeignKey(OrderInstance, on_delete = models.CASCADE, help_text = 'Выберите распоряжение', verbose_name = 'Распоряжение', related_name='orderInstanceBy')

    class Meta:
        ordering = ['date_of_created']
        verbose_name = 'Таблица распоряжения'
        verbose_name_plural = 'Таблиции распоряжений'

    def display_products(self):
        return ', '.join(products.name for products in self.products.all()[:3])

    def __str__(self):
        return f'Распоряжение ({self.order_by.id} - {self.company.name}) '

    display_products.short_description = 'Продукты'
    pass

class TimeExecutionUser(models.Model):
    """ This is model in base for remeber time when user accept and disaccept some order.
    """
    time = models.DateTimeField(null = True, blank = True, default=timezone.now, verbose_name = 'Дата и время подписания распоряжения')
    time_got_order = models.DateTimeField(null = True, blank = True, default=timezone.now, verbose_name = 'Дата и время получения распоряжения')
    user = models.ForeignKey(User, blank = True, on_delete = models.CASCADE, verbose_name = 'Подписывающий', related_name = 'execution_user')
    order_by = models.ForeignKey(OrderInstance, on_delete = models.CASCADE, help_text = 'Выберите распоряжение', verbose_name = 'Распоряжение', related_name='order_execution_user_time_by')
    got_order = models.BooleanField(default = False, help_text = 'Получил ли пользователь распоряжение', verbose_name = 'Получено ли распоряжение')

    class Meta:
        verbose_name = 'Время подписии'
        verbose_name_plural = 'Время подписей'

    def __str__(self):
        return f'Пользователь: {self.user} - Распоряжение: {self.order_by} '

    pass

crmaaf/apps/core/forms.py
from .models import *
from bootstrap_modal_forms.forms import BSModalModelForm
from crmaaf.apps.core.services.widgets import DateInput
from crmaaf.apps.core.services.user_controlling_worker import add_users_controlling_by_group_to_order
import datetime  


class NewOrderInstanceForm(BSModalModelForm):
    """ This is form will created new order.
    For created order-instance need to only title, date of created and type order,
    other fields must auto will filled itself.
    """

    class Meta:
        model = OrderInstance
        fields = ('title', 'type_order', 'shipment_by')
        exclude = ('due_back',)
        

    def save(self, commit=True): # Auto filled controlling list with users when it will saved.

        self.object = super(BSModalModelForm, self).save(commit=False)

        if not self.request.is_ajax():

            if (self.object.id_document == 0):

                self.object_list = OrderInstance.objects.order_by('id_document')
                if len(self.object_list) == 0:  # if there are no objects
                    self.object.id_document = int(f'1')
                else:
                    self.object.id_document =  int(f'{int(len(self.object_list)) + 1}')

            if self.object.status == 'p':
                self.object.created_by = self.request.user
                self.object.due_back = datetime.date.today()    

            self.object.save()

            add_users_controlling_by_group_to_order(self.object)

            self.transport_pks  = self.object.orderInstanceBy.values_list('transport_order', flat=True)

            for i in Transport.objects.filter(pk__in=self.transport_pks).all():
                for j in i.controlling_transport.all():
                    self.object.controlling.add(j)

        return self.object


class NewinOrderForm(BSModalModelForm):
    """ This is form will created new order to the instance order table,
    but actually it will made individual order and then 
    connected via Forgive Key to the instance order.
    """

    class Meta:
        model = Order
        fields = ('company', 'products', 'date_of_shipment', 
                  'net_weight', 'transport_order', 'transport_number', 'note')
        widgets = {
            'date_of_shipment' : DateInput(
                                        format=('%Y-%m-%d'),
                                        attrs={'type': 'date',
                                               'value': datetime.date.today()}
                                        ),
        }

    def save(self, commit=True): # Auto filled controlling list with users when it will saved.

        self.object = super(BSModalModelForm, self).save(commit=True)

        if not self.request.is_ajax():

            add_users_controlling_by_group_to_order(self.object.order_by)

            for i in self.object.transport_order.controlling_transport.all():
                self.object.order_by.controlling.add(i)

            self.object.save()

        return self.object


class NewCompanyForm(BSModalModelForm):

    class Meta:
        model = Company
        fields = '__all__'
    pass

class NewProductForm(BSModalModelForm):

    class Meta:
        model = Product
        fields = '__all__'
    pass

class NewTransportForm(BSModalModelForm):

    class Meta:
        model = Transport
        fields = ('name', 'controlling_transport')
    pass

class NewShipmentForm(BSModalModelForm):

    class Meta:
        model = Shipment
        fields = ('name',)
    pass

crmaaf/apps/core/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

    <head>
        {% block title %}<title>AsiaAgroFood JSC</title>{% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="{% static 'css/chart.min.css' %}">
        <script src="{% static 'js/jquery-3.5.1.min.js'%}"></script>
        <script src="{% static 'js/jquery-ui.min.js'%}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
        <script src="{% static 'js/chart.min.js' %}"></script>
        <script src="{% static 'js/extra-logic.js'%}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/custom.styles.css' %}">
        <link rel="shortcut icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
    </head>

<body>    
    <!-- Top bar with navbar and menu seciton.-->
     {% if user.is_authenticated %}
        {% if  request.resolver_match.url_name != 'order_detail_print' %}
            <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-dark border-bottom shadow-sm noprint">
                <h5 class="my-0 mr-md-auto font-weight-normal  text-light">AsiaAgroFood JSC 
                <small class="text-muted ">{% block subtitle %}{% endblock %}</small>
                </h5>

                    <!-- This is menu-->
                    {% block navbar %}

                    <nav class="my-2 my-md-0 mr-md-3 navbar-dark">
                        <a class="btn p-2 text-light" href="{% url 'index' %}">Главная страница</a>

                        <div class="btn-group">
                            <button type="button" class="btn dropdown-toggle text-light" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Документация
                            </button>
                            <div class="dropdown-menu">
                                {% if perms.core.view_order %}
                                    <a class="dropdown-item p-2 text-dark" href="{% url 'orders' %}">Распоряжения на отгрузку готовой продукции</a>
                                {% endif %}
                                {% if perms.railway.view_railwayorder %}
                                    <a class="dropdown-item p-2 text-dark" href="{% url 'railway_order_page' %}">ЖД Документация</a>
                                {% endif %}
                            </div>
                        </div>

                        {% if perms.core.add_order %}
                        <div class="btn-group">
                            <button type="button" class="btn dropdown-toggle  text-light" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Реквизиты
                            </button>
                            <div class="dropdown-menu">
                                {% if perms.core.view_company %}
                                    <a class="dropdown-item p-2 text-dark" href="{% url 'company' %}">Компании</a>
                                {% endif %}
                                {% if perms.core.view_product %}
                                    <a class="dropdown-item p-2 text-dark" href="{% url 'product' %}">Продукты</a>
                                {% endif %}
                                {% if perms.core.view_transport %}
                                    <a class="dropdown-item p-2 text-dark" href="{% url 'transport' %}">Транспортировка</a>
                                {% endif %}
                                {% if perms.core.view_shipment %}
                                    <a class="dropdown-item p-2 text-dark" href="{% url 'shipment' %}">Отгрузки</a>
                                {% endif %}
                            </div>
                        </div>
                        {% endif %}

                    </nav>
                    {% endblock %}

                    <medium class="pr-3 text-light"> <strong>  {{ user.last_name }} {{ user.first_name }} </strong> </medium>
                    <div class="btn-toolbar">
                        <a class="btn btn-primary mt-2" href="{% url 'logout'%}?next={% url 'login' %}?next={{request.path}}">Выйти</a> 
                        {% if user.is_superuser %} <a class="btn btn-success mt-2 ml-2" href="/admin">Admin Panel</a> {% endif %}
                    </div>
            </header>
        {% endif %}

    <!-- Main section with content -->
    <section>
        <div class="container">
            {% block content %}
            {% endblock %}
    
            {% load tags %}
            {% block pagination %}
                {% if is_paginated %}
                    {% if page_obj.has_previous %}
                        <a href="?{% param_replace page=1 %}">Первая</a>
                        {% if page_obj.previous_page_number != 1 %}
                        <a href="?{% param_replace page=page_obj.previous_page_number %}">Предыдущая</a>
                        {% endif %}
                    {% endif %}

                    Страница {{ page_obj.number }} из {{ paginator.num_pages }}

                    {% if page_obj.has_next %}
                        {% if page_obj.next_page_number != paginator.num_pages %}
                        <a href="?{% param_replace page=page_obj.next_page_number %}">Следующая</a>
                        {% endif %}
                        <a href="?{% param_replace page=paginator.num_pages %}">Последняя</a>
                    {% endif %}

                    <p>Элементов {{ page_obj.start_index }}—{{ page_obj.end_index }}</p>
                    {% endif %}
            {% endblock %} 
        </div>
    </section>

    {% if  request.resolver_match.url_name != 'order_detail_print' %}
    <!-- Footer -->
    <footer class="container noprint">
        <div class="d-flex justify-content-between align-items-center text-center my-md-5 pt-md-5 border-top">
            <div>
                <medium class="d-block text-muted"><a href="http://asiaagrofood.kz">AsiaAgroFood JSC</a></medium>
                <small class="d-block text-muted">© 2021 г. Все права защищены.</small>
            </div>

            <div>
                <small class="d-block text-muted">Version 2</small>
            </div>
        </div>
    </footer>
    {% endif %}

  <!-- Login -->
  {% else %}

    <div class="container" id="login_field">
        <div class="d-flex align-items-center flex-column shadow p-3 mb-5 bg-white rounded border" >
        
            <h1 class = "font-weight-bold m-4"> АО «АзияАгроФуд»</h1>

            <div>
                {% block login_content%}
                {% endblock%}
            </div>

        </div>
    </div>
  {% endif %}
  <!-- Login -->
</body>
</html>

crmaaf/apps/core/templates/index.html
{% extends "base_generic.html" %}


{% block subtitle %}
// Главная
{% endblock %}

{% block content %}

  <h4>Информационный портал АО «АзияАгроФуд»</h4>

  <!-- Dashboard Cards-->
  <div class="row">
    <div class="col-sm-6 mb-2"> 
      <div class="card">
        <h5 class="card-header"><a href="{% url 'orders' %}">Распоряжений</a> <br/> на согласование</h5>
        <div class="card-body">
          <h3 class="card-title">Количество: {{ num_order_instance_consideration }}</h3>
          <p class="card-text mb-0 text-muted">
            <span class="text-success mr-2">
            {% if last_order_instance_consideration %}
            <i class="mdi mdi-arrow-up-bold"><a href="{{ last_order_instance_consideration.get_absoulute_url }}"> {{ last_order_instance_consideration.title }} </a> </i>
            </span>
            <span class="text-nowrap">Последнее</span>  
            {% else %}
            <span class="text-success mr-2"> <i class="mdi mdi-arrow-up-bold"> Распоряжений на рассмотрение нету. </i></span> 
            {% endif %}
          </p>
        </div>
      </div>
    </div>

    <div class="col-sm-6 mb-2"> 
        <div class="card">
          <h5 class="card-header"><a href="{% url 'orders' %}">Распоряжения</a> <br/> одобренные</h5>
          <div class="card-body">
            <h3 class="card-title">Количество: {{ num_order_instance_allow }}</h3>
            <p class="card-text mb-0 text-muted">
              <span class="text-success mr-2">
              {% if last_order_instance_allow %}
                <i class="mdi mdi-arrow-up-bold"><a href="{{ last_order_instance_allow.get_absoulute_url }}"> {{ last_order_instance_allow.title }} </a> </i>
                </span>
                <span class="text-nowrap">Последнее</span>  
              {% else %}
                <span class="text-success mr-2"> <i class="mdi mdi-arrow-up-bold"> Распоряжений на процессе нету. </i></span> 
              {% endif %}
            </p>
        </div>
      </div>
    </div>

    <div class="col-sm-6 mb-2"> 
        <div class="card">
          <h5 class="card-header"><a href="{% url 'orders' %}">Распоряжения</a> <br/> неодобренные</h5>
          <div class="card-body">
            <h3 class="card-title">Количество: {{ num_order_instance_disallow }}</h3>
            <p class="card-text mb-0 text-muted">
              <span class="text-success mr-2">
              {% if last_order_instance_disallow %}
                <i class="mdi mdi-arrow-up-bold"><a href="{{ last_order_instance_disallow.get_absoulute_url }}"> {{ last_order_instance_disallow.title }} </a> </i>
                </span>
                <span class="text-nowrap">Последнее</span>  
              {% else %}
                <span class="text-success mr-2"> <i class="mdi mdi-arrow-up-bold"> Распоряжений на процессе нету. </i></span> 
              {% endif %}
            </p>
        </div>
      </div>
    </div>
  </div>
  <!-- Dashboard Cards-->
{% endblock %}