crmaaf/apps/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('', views.index, name = 'index'),
    path('api/chart_data/', views.ChartAPIView.as_view()),
    path('orders/', views.OrdersListView.as_view(), name = 'orders'),

    path('orders/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('orders/<str:pk>', views.OrderDetailView.as_view(), name='order_detail'),
    path('orders/<str:pk>/print/', views.PrintOrderDetailView.as_view(), name='order_detail_print'),
    path('orders/<str:pk>/delete/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('orders/<str:pk>/update/', views.OrderUpdateView.as_view(), name='order_update'),

    path('orders/<int:pk>/deletefield/', views.inOrderDeleteView.as_view(), name='in_order_delete'),
    path('orders/<int:pk>/updatefield/', views.inOrderUpdateView.as_view(), name='in_order_update'),
    path('orders/<str:pk>/createfield/', views.inOrderCreateView.as_view(), name='in_order_create'),
    path('orders/<str:pk>/sendorder/', views.inSendOrder, name='in_order_send'),

    path('orders/<str:pk>/alloworder/', views.allowOrder, name='allow_order'),
    path('orders/<str:pk>/disalloworder/', views.disallowOrder, name='disallow_order'),
    path('orders/<str:pk>/allowOrderManager/', views.allowOrderManager, name='allow_order_manager'),

    path('company/', views.companyListView.as_view(), name = 'company'),
    path('company/create/', views.companyCreateView.as_view(), name = 'company_create'),
    path('company/<int:pk>/update/', views.companyUpdateView.as_view(), name = 'company_update'),
    path('company/<int:pk>/delete/', views.companyDeleteView.as_view(), name = 'company_delete'),

    path('product/', views.productListView.as_view(), name = 'product'),
    path('product/create/', views.productCreateView.as_view(), name = 'product_create'),
    path('product/<int:pk>/update/', views.productUpdateView.as_view(), name = 'product_update'),
    path('product/<int:pk>/delete/', views.productDeleteView.as_view(), name = 'product_delete'),

    path('transport/', views.transportListView.as_view(), name = 'transport'),
    path('transport/create/', views.transportCreateView.as_view(), name = 'transport_create'),
    path('transport/<int:pk>/update/', views.transportUpdateView.as_view(), name = 'transport_update'),
    path('transport/<int:pk>/delete/', views.transportDeleteView.as_view(), name = 'transport_delete'),

    path('shipment/', views.shipmentListView.as_view(), name = 'shipment'),
    path('shipment/create/', views.shipmentCreateView.as_view(), name = 'shipment_create'),
    path('shipment/<int:pk>/update/', views.shipmentUpdateView.as_view(), name = 'shipment_update'),
    path('shipment/<int:pk>/delete/', views.shipmentDeleteView.as_view(), name = 'shipment_delete'),
]

crmaaf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-interface/', include('rest_framework.urls')),

    path('railway/', include('crmaaf.apps.railwayplatform.urls')),
    path('core/', include('crmaaf.apps.core.urls')),
    path('', include('crmaaf.apps.aaf.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crmaaf/apps/core/models.py
from django.db import models
from django.urls import reverse 
from django.contrib.auth.models import User
from django.utils import timezone
import uuid


class Product(models.Model):
    """ Products our company like flour, molasses and etc.
    """

    name = models.CharField(max_length = 120, help_text = 'Напишите Названия Продукта', verbose_name = 'Наименнование')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        
    pass

class Transport(models.Model):
    """ Actually the model is transportation.
    """

    name = models.CharField(max_length = 120, help_text = 'Напишите назваиня Типа Транспортировки', verbose_name = 'Наименнование')
    controlling_transport = models.ManyToManyField(User, blank = True, help_text = 'Распоряжение получит', verbose_name = 'Распоряжение получит', related_name='controlling_transport')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']
        verbose_name = 'Транспортировка'
        verbose_name_plural = 'Транспортировки'

    pass

class Shipment(models.Model):
    """ Model for shipments types.
    """

    name = models.CharField(max_length = 120, help_text = 'Напишите названия отгрузки', verbose_name = 'Наименнование')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']
        verbose_name = 'Отгрузка груза'
        verbose_name_plural = 'Отгрузки груза'

    pass

class Company(models.Model):
    """ The company which will be added to the "order" list 
    and may for search by users any contacts information about company.
    """ 

    name = models.CharField(max_length = 120, help_text = 'Напишите названия Компании', verbose_name = 'Наименнование')
    contact_name = models.CharField(max_length = 120, help_text = 'Напишите Ф.И.О.', blank = True, verbose_name = 'Контактное Имя')
    contact_phone = models.CharField(max_length = 16, help_text = 'Напишите Номер Телефона', blank = True, verbose_name = 'Контактный Телефон')
    contact_email = models.EmailField(help_text = 'Укажите Адресс Электронной Почты', blank = True, verbose_name = 'Контактный Е-Майл')
    note = models.TextField(max_length = 1000, help_text = 'Введите Описание', blank = True, verbose_name = 'Заметки')

    class Meta:
        ordering = ['-name']
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

    def __str__(self):
        return self.name

    def get_absoulute_url(self):
        return reverse('company-detail', args=[str(self.id)])

    pass

class OrderInstance(models.Model):
    """  This is model will be group up all the "orders" 
    to the alone "order" with tables, "controlling users" list and etc.
    """

    title = models.CharField(max_length = 120, help_text = 'Наименнование распоряжения', verbose_name = 'Наименнование')
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, help_text = 'Уникальный ID', verbose_name = 'Уникальный ID')
    id_document = models.IntegerField(help_text = 'Уникальный ID', verbose_name = 'Уникальный ID', blank = True, default = 0)
    due_back = models.DateField(null = True, blank = True, verbose_name = 'Дата подачи распоряжения') 
    date_allow = models.DateField(null = True, blank = True, verbose_name = 'Дата согласования распоряжения')
    date_finish = models.DateField(null = True, blank = True, verbose_name = 'Дата исполнения распоряжения')

    controlling = models.ManyToManyField(User, blank = True, help_text = 'Распоряжение получит', verbose_name = 'Распоряжение получит', related_name = 'controlling')
    controlling_allow = models.ManyToManyField(User, blank = True, help_text = 'Распоряжение одобрил', verbose_name = 'Распоряжение одобрил', related_name = 'controlling_allow')
    controlling_disallow = models.ManyToManyField(User, blank = True, help_text = 'Распоряжение неодбрил', verbose_name = 'Распоряжение неодбрил', related_name = 'controlling_disallow')

    created_by = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = 'Исполнитель распоряжения', related_name = 'created_by')
    shipment_by = models.ForeignKey(Shipment, on_delete = models.CASCADE, help_text = 'Выберите отгрузку', blank = True, null=True, default=None, verbose_name = 'Отгрузка от', related_name = 'shipment_by')

    LOAN_STATUS = (
        ('p', 'В Процессе'),
        ('w', 'На согласование'),
        ('j', 'На исполнение'),
        ('a', 'Исполнено'),
        ('d', 'Отказано'),
    )

    LOAN_TYPE_ORDER = (
        ('kp', 'Паточный'),
        ('kz', 'Комбикормовый завод'),
        ('ml', 'Мельница'),
    )

    status = models.CharField(max_length = 16, choices = LOAN_STATUS, blank = True, default = 'p', verbose_name = 'Статус')
    type_order = models.CharField(max_length = 16, choices = LOAN_TYPE_ORDER, default = 'kp', verbose_name = 'Тип распоряжения')


    class Meta:
        ordering = ['-due_back', '-status']
        permissions = (("sign_order", "Can sign order"), ("sign_order_manager", "Sign order manager"),)
        verbose_name = 'Распоряжение'
        verbose_name_plural = 'Распоряжения'

    def display_created_by(self):
        self.full_name = '' #For if the user haven't name or last name.

        if self.created_by.last_login:
            self.full_name = self.full_name + f'{self.created_by.last_name}'
        if self.created_by.first_name:
            self.full_name = self.full_name + f' {self.created_by.first_name[0]}.'

        return self.full_name

    def __str__(self):
        return f'{self.title}'

    def get_absoulute_url(self):
        return reverse('order_detail', args=[str(self.id)])

    display_created_by.short_description = 'Создатель Распоряжения'
    pass

class Order(models.Model):
    """ This is class is table "order" it will be related to some "order instance",
    but mostly with one "order instance".
    """
    
    company = models.ForeignKey(Company, on_delete = models.CASCADE, verbose_name = 'Компания')
    products = models.ManyToManyField(Product, help_text = 'Выберите Продукт', verbose_name = 'Продукция')
    date_of_created = models.DateField(auto_now_add = True, verbose_name = 'Дата Создания')
    date_of_shipment = models.DateField(help_text = 'Укажите Дату Отгрузки', verbose_name = 'Дата Отгрузки')
    net_weight = models.DecimalField(max_digits = 19, decimal_places = 2, help_text = 'Введите вес', verbose_name = 'Вес Нетто, тн')
    transport_order = models.ForeignKey(Transport, on_delete = models.CASCADE, help_text = 'Выберите тип транспорортировки', verbose_name = 'Транспортировка')
    transport_number = models.IntegerField(blank = True, default = 0, help_text = 'Количество транспорта', verbose_name = 'Количество транспорта')
    note = models.TextField(max_length = 1000, help_text = 'Введите описание', blank = True, verbose_name = 'Заметки')
    order_by = models.ForeignKey(OrderInstance, on_delete = models.CASCADE, help_text = 'Выберите распоряжение', verbose_name = 'Распоряжение', related_name='orderInstanceBy')

    class Meta:
        ordering = ['date_of_created']
        verbose_name = 'Таблица распоряжения'
        verbose_name_plural = 'Таблиции распоряжений'

    def display_products(self):
        return ', '.join(products.name for products in self.products.all()[:3])

    def __str__(self):
        return f'Распоряжение ({self.order_by.id} - {self.company.name}) '

    display_products.short_description = 'Продукты'
    pass

class TimeExecutionUser(models.Model):
    """ This is model in base for remeber time when user accept and disaccept some order.
    """
    time = models.DateTimeField(null = True, blank = True, default=timezone.now, verbose_name = 'Дата и время подписания распоряжения')
    time_got_order = models.DateTimeField(null = True, blank = True, default=timezone.now, verbose_name = 'Дата и время получения распоряжения')
    user = models.ForeignKey(User, blank = True, on_delete = models.CASCADE, verbose_name = 'Подписывающий', related_name = 'execution_user')
    order_by = models.ForeignKey(OrderInstance, on_delete = models.CASCADE, help_text = 'Выберите распоряжение', verbose_name = 'Распоряжение', related_name='order_execution_user_time_by')
    got_order = models.BooleanField(default = False, help_text = 'Получил ли пользователь распоряжение', verbose_name = 'Получено ли распоряжение')

    class Meta:
        verbose_name = 'Время подписии'
        verbose_name_plural = 'Время подписей'

    def __str__(self):
        return f'Пользователь: {self.user} - Распоряжение: {self.order_by} '

    pass

crmaaf/apps/core/forms.py
from .models import *
from bootstrap_modal_forms.forms import BSModalModelForm
from crmaaf.apps.core.services.widgets import DateInput
from crmaaf.apps.core.services.user_controlling_worker import add_users_controlling_by_group_to_order
import datetime  


class NewOrderInstanceForm(BSModalModelForm):
    """ This is form will created new order.
    For created order-instance need to only title, date of created and type order,
    other fields must auto will filled itself.
    """

    class Meta:
        model = OrderInstance
        fields = ('title', 'type_order', 'shipment_by')
        exclude = ('due_back',)
        

    def save(self, commit=True): # Auto filled controlling list with users when it will saved.

        self.object = super(BSModalModelForm, self).save(commit=False)

        if not self.request.is_ajax():

            if (self.object.id_document == 0):

                self.object_list = OrderInstance.objects.order_by('id_document')
                if len(self.object_list) == 0:  # if there are no objects
                    self.object.id_document = int(f'1')
                else:
                    self.object.id_document =  int(f'{int(len(self.object_list)) + 1}')

            if self.object.status == 'p':
                self.object.created_by = self.request.user
                self.object.due_back = datetime.date.today()    

            self.object.save()

            add_users_controlling_by_group_to_order(self.object)

            self.transport_pks  = self.object.orderInstanceBy.values_list('transport_order', flat=True)

            for i in Transport.objects.filter(pk__in=self.transport_pks).all():
                for j in i.controlling_transport.all():
                    self.object.controlling.add(j)

        return self.object


class NewinOrderForm(BSModalModelForm):
    """ This is form will created new order to the instance order table,
    but actually it will made individual order and then 
    connected via Forgive Key to the instance order.
    """

    class Meta:
        model = Order
        fields = ('company', 'products', 'date_of_shipment', 
                  'net_weight', 'transport_order', 'transport_number', 'note')
        widgets = {
            'date_of_shipment' : DateInput(
                                        format=('%Y-%m-%d'),
                                        attrs={'type': 'date',
                                               'value': datetime.date.today()}
                                        ),
        }

    def save(self, commit=True): # Auto filled controlling list with users when it will saved.

        self.object = super(BSModalModelForm, self).save(commit=True)

        if not self.request.is_ajax():

            add_users_controlling_by_group_to_order(self.object.order_by)

            for i in self.object.transport_order.controlling_transport.all():
                self.object.order_by.controlling.add(i)

            self.object.save()

        return self.object


class NewCompanyForm(BSModalModelForm):

    class Meta:
        model = Company
        fields = '__all__'
    pass

class NewProductForm(BSModalModelForm):

    class Meta:
        model = Product
        fields = '__all__'
    pass

class NewTransportForm(BSModalModelForm):

    class Meta:
        model = Transport
        fields = ('name', 'controlling_transport')
    pass

class NewShipmentForm(BSModalModelForm):

    class Meta:
        model = Shipment
        fields = ('name',)
    pass

crmaaf/apps/core/templates/core/order/order_detail.html
{% extends "base_generic.html" %}


{% block subtitle %}
 // {{ orders_detail.title }}
{% endblock %}

{% block content %}

{% load tags %}

  <!-- Menu for users -->
  <div class="navbar navbar-light bg-light border shadow-sm mb-2">

    <div class="mr-2">

      <button type="button" class="btn btn-dark" onclick="location.href='{% url 'orders' %}'">Назад</button>

      <div class="btn-group">
        {% for i in orders_detail.controlling.all %}
          {% if perms.core.sign_order and user == i and orders_detail.status != 'p'%} <!-- if order's status equals "For consideration" then show that buttons. -->
            <button type="button" class="btn btn-primary" onclick="location.href='{% url 'allow_order' orders_detail.pk %}';"> {% if request.user|has_group:'BOSS' %} Согласовано {% else %} Исполненно {% endif %}</button>
            <button type="button" class="btn btn-dark" onclick="location.href='{% url 'disallow_order' orders_detail.pk %}';">Отказать</button>
          {% endif %}
        {% endfor %}

        {% if perms.core.change_order and orders_detail.status != 'a' and orders_detail.status != 'd'%} 
          {% if orders_detail.status == 'p' or orders_detail.status == 'w' %}
            <button type="button" class="modal-form btn btn-primary" data-form-url="{% url 'in_order_create' orders_detail.pk %}" name="button">Добавить поле</button>
          {% endif %}
        {% endif %}

        {% if perms.core.change_order and orders_detail.status == 'p' %} <!-- Sent that order all controlling people. -->
            <button type="button" class="btn btn-dark" onclick="location.href='{% url 'in_order_send' orders_detail.pk %}'">Отправить</button>
        {% endif %}
      </div>
    </div>

    <button class="btn" onclick="location.href='{% url 'order_detail_print' orders_detail.pk %}'"> <!-- Print page button-->
      {% load static %}
      <img src="{% static 'img/icon_print.svg' %}" />
    </button>

  </div>

  <!-- Other elements -->
  {% include "core/form/modal_form.html" %} 

  {% include "core/order/order_detail_table.html" %}

  {% include "core/order/order_detail_controlling_logic.html" %}

{% endblock %}

crmaaf/apps/core/templates/core/order/order_detail_controlling_logic.html
{% load tags %}


<!-- The Antuor to that document-->
<div class="d-flex justify-content-between p-2 mb-2"> 
    <div> 
        <strong> Статус распоряжения - </strong> 
        <strong class='text-primary'> {{ orders_detail.get_status_display }} </strong>
    </div>
</div>

{% if orders_detail.date_allow or orders_detail.date_finish %}
<div class="d-flex justify-content-between p-2 mb-2"> 
    {% if orders_detail.date_allow %} 
        <div> <medium class="text-muted">
            Дата согласования:   {{ orders_detail.date_allow }} 
        </div> </medium> 
    {% endif %}

    {% if orders_detail.date_finish %} 
        <div> <medium class="text-muted"> 
            Дата исполнения:  {{ orders_detail.date_finish }} 
        </div> </medium> 
    {% endif %}
</div>
{% endif %}
<!-- The Antuor to that document-->

<!-- The controlling people-->
<!-- BOSS BEGIN -->
<div class="pl-1 pb-1"> <strong> Утверждают: </strong> </div>

{% if orders_detail.controlling.all %}
  {% for controlling in orders_detail.controlling.all %} 
      {% if controlling|has_group:'BOSS' or controlling|has_group:'CommercialDir'%}
      <div class="d-flex justify-content-between pl-1 pb-2">
        <div> {{controlling.userprofile.user_position}}</div>
        <div class="d-flex justify-content-between">
          {{ controlling.last_name }} {{ controlling.first_name.0 }}. - &nbsp;
          <div>
          <strong class="text-primary">{{controlling.userprofile.user_in_working}} </strong> <!-- in working for boss -->
          {% for time_execution in orders_detail.order_execution_user_time_by.all %}
            {% if time_execution.user == controlling %}
              <div>
                <strong>Ознакомлен(а): </strong> {{ time_execution.time_got_order }}
              </div>
            {% endif %}  
          {% endfor %}
          </div>
        </div>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}

    {% for controlling in orders_detail.controlling_allow.all %} 
      {% if controlling|has_group:'BOSS' or controlling|has_group:'CommercialDir' %}
        <div class="d-flex justify-content-between p-1 pb-2">

        <div> {{controlling.userprofile.user_position}}</div>
        <div class="d-flex justify-content-between">
        {{ controlling.last_name }} {{ controlling.first_name.0 }}. - &nbsp;
        <div>
        <strong class='text-primary'>{{controlling.userprofile.user_accept}} </strong>  <!-- accept for boss -->
          {% for time_execution in orders_detail.order_execution_user_time_by.all %}
            {% if time_execution.user == controlling %}
              {% if time_execution.time %} {{ time_execution.time }} {% endif %}
              <div>
              <strong> Ознакомлен(а): </strong>{{ time_execution.time_got_order }}
              </div>
            {% endif %} 
          {% endfor %}
          </div>
        </div>
      </div>
      {% endif %}
    {% endfor %}

  {% for controlling in orders_detail.controlling_disallow.all %}
      {% if controlling|has_group:'BOSS' or controlling|has_group:'CommercialDir' %}
        <div class="d-flex justify-content-between pl-1 pb-2">
          <div> {{controlling.userprofile.user_position}}</div>
          <div class="d-flex justify-content-between">
            {{ controlling.last_name }} {{ controlling.first_name.0 }}. - &nbsp;
            <div>
            <strong class='text-primary'> {{controlling.userprofile.user_disaccept}} </strong> <!-- disaccept -->
              {% for time_execution in orders_detail.order_execution_user_time_by.all %}
                {% if time_execution.user == controlling %}
                  {% if time_execution.time %} {{ time_execution.time }} {% endif %}
                    <div>
                      <strong>Ознакомлен(а): </strong> {{ time_execution.time_got_order }}
                    </div>
                  {% endif %}  
                {% endfor %}
          </div>
        </div>
      </div>
      {% endif %}
  {% endfor %}

<!-- BOSS END -->
<!-- USER BEGIN -->
<div class="pl-1 pb-1"> <strong> Распоряжение получено: </strong> </div>

{% if orders_detail.controlling.all %}
  {% for controlling in orders_detail.controlling.all %} 
      {% if not controlling|has_group:'BOSS' and not controlling|has_group:'CommercialDir' %}
        <div class="d-flex justify-content-between pl-1 pb-2">


        <div>

          {% if perms.core.sign_order_manager and orders_detail.status == 'j' %}
            <button type="button" class="btn btn-primary remove_on_print" onclick="location.href=' {% url 'allow_order_manager' orders_detail.pk %}?user_id={{controlling.id}}'; "> Готово </button> 
          {% endif %}

          {{controlling.userprofile.user_position}}
        </div>

        <div class="d-flex justify-content-between">
            {% if orders_detail.status == 'w' or orders_detail.status == 'p' %}
                {{ controlling.last_name }} {{ controlling.first_name.0 }}. - &nbsp;<strong class='text-primary'> В ожидание </strong> 
            {% else %}
                {{ controlling.last_name }} {{ controlling.first_name.0 }}. - &nbsp;
            <div>
              <strong class='text-primary'> {{controlling.userprofile.user_in_working}} </strong> <!-- in working for users -->
              {% for time_execution in orders_detail.order_execution_user_time_by.all %}
                {% if time_execution.user == controlling %}
                  <div>
                  <strong>Ознакомлен(а): </strong>{{ time_execution.time_got_order }}
                  </div>
                {% endif %}  
              {% endfor %}
            </div>
            {% endif %}
        </div>
  </div>
  {% endif %}
 {% endfor %}
{% endif %}


  {% for controlling in orders_detail.controlling_disallow.all %}
      {% if not controlling|has_group:'BOSS' and not controlling|has_group:'CommercialDir' %}
          <div class="d-flex justify-content-between p-1 mb-1">
          <div> {{controlling.userprofile.user_position}}</div>
          <div class="d-flex justify-content-between">
            {{ controlling.last_name }} {{ controlling.first_name.0 }}. - &nbsp;
            <div>
            <strong class='text-primary'> {{controlling.userprofile.user_disaccept}} </strong> <!-- disaccept -->
              {% for time_execution in orders_detail.order_execution_user_time_by.all %}
                {% if time_execution.user == controlling %}
                  {% if time_execution.time %} {{ time_execution.time }} {% endif %}
                    <div>
                    <strong>Ознакомлен(а): </strong> {{ time_execution.time_got_order }}
                    </div>
                  {% endif %}  
                {% endfor %}
            </div>
          </div>
        </div>
      {% endif %}
  {% endfor %}

    {% for controlling in orders_detail.controlling_allow.all %} 
      {% if not controlling|has_group:'BOSS' and not controlling|has_group:'CommercialDir' %}
            <div class="d-flex justify-content-between p-1 mb-1">
            <div> {{controlling.userprofile.user_position}}</div>
            <div class="d-flex justify-content-between">
                {{ controlling.last_name }} {{ controlling.first_name.0 }}. - &nbsp;
              <div>
                <strong class='text-primary'> {{controlling.userprofile.user_accept}} </strong> <!-- accept for user -->
                {% for time_execution in orders_detail.order_execution_user_time_by.all %}
                  {% if time_execution.user == controlling %}
                    {% if time_execution.time %} {{ time_execution.time }} {% endif %}
                    <div>
                    <strong>Ознакомлен(а): </strong>{{ time_execution.time_got_order }}
                    </div>
                  {% endif %} 
                {% endfor %}
          </div>
        </div>
      </div>
      {% endif %}
    {% endfor %}

  <div class="pt-2 pl-1 pb- 2"><strong> Испольнитель: </strong></div> 
  <div class="pl-1 d-flex justify-content-between">
    <div>{{ orders_detail.created_by.userprofile.user_position}}</div> 
    <div>{{ orders_detail.display_created_by }}</div> 
  </div>
<!-- USER END -->
<!-- The controlling people-->

crmaaf/apps/core/templates/core/order/order_detail_print.html
  {% extends "base_generic.html" %}

  {% block content %}
  <div id="print" class="body-print">
  <!-- Submenu -->
   <div class="navbar navbar-light bg-light border shadow-sm mb-2 mt-4">

    <div class="mr-2">
      <button type="button" class="btn btn-dark" onclick="location.href='{% url 'order_detail' orders_detail.pk %}'">Назад</button>
    </div>

    <button class="btn btn-dark" onclick="window.print()">Распечатать</button>

  </div>
  <!-- SubMenu -->
  
  <div id="print" class="text-center">
    {% include "core/order/order_detail_table.html" %}
  </div>

  <div id="print" class="footer-print mt-3">
    {% include "core/order/order_detail_controlling_logic.html" %}
  </div>

{% endblock %}

crmaaf/apps/core/templates/core/order/order_table.html
{% load static %}    
{% load tags %}

<table class="table table-bordered table-sm text-center">

    <thead>
        <tr class="thead-light">
        <th width="1%"> № </th>
        <th width="14%"> Номер док.</th>
        <th width="15%"> Название </th>
        <th width="15%"> Дата</th>
        <th width="15%"> Исполнитель </th>
        <th width="15%"> Статус </th>
        <th width="10%"> Тип </th>
        {% if perms.core.add_order %} <th width="10%">Действия</th> {% endif %}
    </thead>

    <tbody>
      {% for i in object_list %}
      <tr class="url_table_row move_to_detail_page get_order
        {% for j in i.order_execution_user_time_by.all %}
          {% if user == j.user and j.got_order %} 
            got_order 
          {% elif not user == j.user and j.got_order and not i.status == 'p' %} 
            got_order
          {% endif %}
        {% endfor %}" data-form-url="{{ i.get_absoulute_url }}" role="button">
          <td><strong>{{ forloop.counter }}</strong></td>
          <td>№0{{ i.id_document }}{{ i.type_order|upper }}</td>
          <td>{{ i.title }}</td>
          <td>{{ i.due_back }}</td>
          <td>{{ i.display_created_by }}</td>
          <td>{{ i.get_status_display }}</td>
          <td>{{ i.get_type_order_display }}</td>
          {% if perms.core.add_order %} 
          <td class="action">
              {% if i.status == 'p' %}
              <button type="button" class="modal-form btn btn btn-link" data-form-url="{% url 'order_update' i.pk %}">
                  <img src="{% static 'img/icon_editable.svg' %}" />
              </button>
              {% endif %}
              <button type="button" class="modal-form btn btn btn-link" data-form-url="{% url 'order_delete' i.pk %}">
                  <img src="{% static 'img/icon_crosshair.svg' %}" />
              </button>
          </td>
          {% endif %}
      </tr>
      {% empty %}
        <tr>
          <td colspan="{% if perms.core.add_order %}7{% else %}6{% endif %}">Нет данных</td>
        </tr>
      {% endfor %}
    </tbody>

  </table>
  